apiVersion: v1
kind: Secret
metadata:
  name: skillforge-secrets
  namespace: skillforge
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo:27017/skillforge"
  JWT_SECRET: "replace_me"
  GEMINI_API_KEY: "replace_me"
